### ISSUE TITLE
Option to wait for completion?

### ISSUE THREAD

**Issue by jason-kates-informa** [kerma/defaultbrowser#20]
It would be great to be able to add this to a shell script and have a way defaultbrowser wait until the dialog box has been closed before continuing on.

ie:
defaultbrowser firefox &&next item&&defaultbrowser chrome

Thanks in advance.

**Comment by kerma** [comment]
There is no real way of doing this correctly. MacOS does not expose anything that I could tap into to figure once the dialog box has been closed. At least I'm not aware of anything. 

Technically it would be possible to "sleep" and check whether the default has been changed in loop for a while. But that would be a kind of a hack, and I would need to make some assumptions about what's the expected behavior for the end user. 

So I think it's better to wrap the defaultbrowser binary with a shell script that does what you expect. For example, in zsh this could work:

```zsh
defaultbrowser $1

for n in {1..10}; do
    if [[ $(defaultbrowser | grep -c "* $1") -eq 0 ]]; then
        sleep 1
    fi
done
```

You can add more to exit with 1 if timeout passes etc.
